### ISSUE TITLE
[Feature] Show username only when using ssh like prezto.

### ISSUE THREAD

**Issue by pickfire** [schachmat/slcp#2]

**Comment by schachmat** [comment]
I don't think that would be useful. You basically could not distinguish if you're root or a normal user on the local host then.

**Comment by pickfire** [comment]
> I don't think that would be useful. You basically could not distinguish if you're root or a normal user on the local host then.

No, I don't mean **root**, I mean to display nothing from _username_ if using as normal user, display **red** when using as root, and display it like:

![2015-05-16-220857_747x872_scrot](https://cloud.githubusercontent.com/assets/4687791/7666469/1ad7d4b0-fc19-11e4-9292-c017a00d78ef.png)

**Comment by schachmat** [comment]
Heyho @pickfire,

Adding the necessary code complexity to achieve this is probably not worth it. Think about it, this is no new functionality, it is just hiding a part of the output in certain circumstances which might be useful nevertheless. If you really need it, I think you can easily patch the source yourself. The relevant part is pretty clear.

**Comment by pickfire** [comment]
How much faster can this script be when comparing to `.zshrc`?

**Comment by schachmat** [comment]
Depends on what scale your looking at it from. As I see it (and I've used it for a while) zsh is quite huge and complex. The more code, the more errors. And the least thing I want to fail is my shellprompt because of some complex ssh detection thing. But as I said, you should be able to add the feature yourself easily.
